# Generated by Django 6.0.5 on 2026-05-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
